In [203]:
import pandas as pd
import numpy as np
file1 = "/Users/apple/Workspace/intelliJ/jockey/20181128_3_SameDistance_SameCourse.csv"
file0 = "/Users/apple/Workspace/intelliJ/jockey/20181128_3_DifferentCourse_DifferentDistance.csv"
res0 = pd.read_csv(file0)
res1 = pd.read_csv(file1)
res1=res1.sort_values(by=('lbw'),ascending=True);
res1

,horseNo,horseName,rateDate,draw,standardFinishTime,finishTime,place,lbw,winOdds,distance,course,raceClass,rating,ratingDelta
3,8,DYNAMIC EAGLE(B072),20181003,7,106.09,110.20,2,0.10,4.7,1800,"TURF - ""A"" COURSE",3,61,-2
1,4,BRAVE LEGEND(A260),20181003,6,106.09,110.45,3,2.00,9.7,1800,"TURF - ""A"" COURSE",3,71,-2
4,8,DYNAMIC EAGLE(B072),20180711,7,106.09,109.66,5,2.00,7.8,1800,"TURF - ""A"" COURSE",3,61,-2
2,7,SANGRIA(A065),20180922,5,106.09,107.62,3,2.25,10.0,1800,"TURF - ""A"" COURSE",3,63,-2
0,1,HELENE CHARISMA(A129),20180922,7,106.09,107.95,5,4.25,8.1,1800,"TURF - ""A"" COURSE",3,77,-1
5,8,DYNAMIC EAGLE(B072),20180527,6,106.09,108.43,6,5.75,4.3,1800,"TURF - ""A"" COURSE",3,61,-2

In [217]:

res2=res0.append(res1, ignore_index=True)
#res3=res2[((res2.place <= 4) | (res2.lbw <3 ))& (res2.distance==1800)].sort_values(by=['lbw','rateDate'],ascending=[True,False]);res3
res4=res2[(res2.horseNo ==12)].sort_values(by=('rateDate'),ascending=False);res4

Empty DataFrame
Columns: [horseNo, horseName, rateDate, draw, standardFinishTime, finishTime, place, lbw, winOdds, distance, course, raceClass, rating, ratingDelta]
Index: []

In [117]:
res2=res2[(res2.distance==1000) & (res2.finishTime <= 58)].sort_values(by=('rateDate'),ascending=False);res2;